pipeline {
    agent any

    environment {
        HOME_URL = 'https://www.saucedemo.com/'
        HOME_CREDENTIALS = credentials('SawagLabs-Id')  // contient à la fois username et password
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Create properties file') {
            steps {
                bat 'if not exist src\\test\\resources\\configs mkdir src\\test\\resources\\configs'

                bat """
echo url=%HOME_URL%> src\\test\\resources\\configs\\env-config.properties
echo username=%HOME_CREDENTIALS_USR%>> src\\test\\resources\\configs\\env-config.properties
echo password=%HOME_CREDENTIALS_PSW%>> src\\test\\resources\\configs\\env-config.properties
                """

                bat 'type src\\test\\resources\\configs\\env-config.properties'
            }
        }

        stage('Run Maven Tests') {
            steps {
                bat 'mvn clean test verify'
            }
        }

        stage('Generate Cucumber Report') {
            steps {
                // Assure-toi que maven-cucumber-reporting plugin est configuré dans le pom.xml
                // Le HTML sera généré dans target/cucumber-html-reports
                echo 'Cucumber HTML report will be generated by Maven plugin'
            }
        }

        stage('Publish Cucumber Report') {
            steps {
                publishHTML(target: [
                    reportDir: 'target/report',
                    reportFiles: 'cucumber-report.html',
                    reportName: 'Cucumber Report'
                ])
            }
        }
    }

    post {
        always {
            // Supprime le fichier contenant des credentials
            bat 'del /f /q src\\test\\resources\\configs\\env-config.properties'
        }
    }
}
